language: python
python:
  - 'pypy3.6'
  - 'pypy3.7'
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
  - 'nightly'
install:
  - pip install -e .[dev]
script:
  - coverage run --source=messagebird -m unittest discover -s tests/
  - coverage report --fail-under=80
  - pycodestyle --statistics --max-line-length=120 ./messagebird
  - pycodestyle --statistics --max-line-length=160 ./tests
matrix:
  allow_failures:
  - python: 'nightly'
